### ISSUE TITLE
Error on .recommendCommands()

### ISSUE THREAD

**Issue by karthikb23** [googleapis/nodejs-dlp#149]
I've set all the environment variables and get the below error on running `node inspect.js string "My email address is joe@example.com."`

nodejs-dlp/samples/inspect.js:782 
  .recommendCommands()
   ^

TypeError: require(...).demand(...).command(...).command(...).command(...).command(...).command(...).option(...).option(...).option(...).option(...).option(...).option(...).option(...).example(...).example(...).example(...).example(...).example(...).wrap(...).recommendCommands is not a function
    at Object.<anonymous> (/home/karthikb23/Dev/Wysdom/Prototypes/prototypes/Redaction/nodejs-dlp/samples/inspect.js:782:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by JustinBeckwith** [comment]
@ace-n can you take a look?

**Comment by ace-n** [comment]
@karthikb23 Works for me - try reinstalling your dependencies?
```
rm -rf node_modules && npm install
```

Failing that, try installing `yargs`:
```
npm install --save yargs
```

**Comment by karthikb23** [comment]
I restarted by machine and strangely, this now works. Anyway, thanks for the quick replies!
