### ISSUE TITLE
"Operation was cancelled" when running DLP example

### ISSUE THREAD

**Issue by barryhammen** [googleapis/nodejs-dlp#445]
#### Environment details

  - OS: macOS Catalina (10.15.3)
  - Node.js version: 12.16.1
  - npm version: 6.13.4
  - `@google-cloud/dlp` version: 2.2.0

#### Steps to reproduce
Running a version of your sample:
```
const DLP = require('@google-cloud/dlp');
const dlp = new DLP.DlpServiceClient();
const projectId = '<myprojectid>';

async function inspectString() {
    const string = 'Robert Frost';
    const minLikelihood = 'LIKELIHOOD_UNSPECIFIED';
    const maxFindings = 0;
    const infoTypes = [{ name: 'PERSON_NAME' }, { name: 'US_STATE' }];
    const includeQuote = true;
    const item = { value: string };
    const request = {
        parent: dlp.projectPath(projectId),
        inspectConfig: {
            infoTypes: infoTypes,
            minLikelihood: minLikelihood,
            limits: {
                maxFindingsPerRequest: maxFindings,
            },
            includeQuote: includeQuote,
        },
        item: item
    };
    try {
        const [response] = await dlp.inspectContent(request);
    } catch (err) {
        console.log(err);
    }
}
inspectString();
```
Throws the following error:
```
Error: 1 CANCELLED: The operation was cancelled.
    at Object.callErrorFromStatus (/source/dlp/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/source/dlp/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/source/dlp/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/source/dlp/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/source/dlp/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/source/dlp/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/source/dlp/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.handleTrailers (/source/dlp/node_modules/@grpc/grpc-js/build/src/call-stream.js:256:14)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emit (internal/http2/core.js:297:8) {
  code: 1,
  details: 'The operation was cancelled.',
  metadata: Metadata {
    internalRepr: Map {
      'google.rpc.debuginfo-bin' => [Array],
      'grpc-status-details-bin' => [Array]
    },
    options: {}
  },
  note: 'Exception occurred in retry method that was not classified as transient'
}
```
However, using the same project and credentials, the following python version works just fine:
```
from google.cloud import dlp_v2
client = dlp_v2.DlpServiceClient()
inspect_config = {'info_types': [{ 'name': 'PERSON_NAME' }, { 'name': 'US_STATE' }]}
value = 'Robert Frost'
items_element = {'value': value}
parent = client.project_path("<myprojectid>")
response = client.inspect_content(parent, inspect_config=inspect_config,item=items_element)
print(response)
```

Thanks!

**Comment by alexander-fenster** [comment]
Hi @barryhammen,

We can reproduce this problem and we're investigating. For the time being, please try using the legacy `grpc`:

```
npm install grpc
```
and then pass it to the client constructor:
```js
const DLP = require('@google-cloud/dlp');
const grpc = require('grpc');
const dlp = new DLP.DlpServiceClient({grpc});
```

**Comment by alexander-fenster** [comment]
@barryhammen Please upgrade your dependencies to fix the issue. Make sure `npm ls @grpc/grpc-js` shows v0.7.7.

**Comment by barryhammen** [comment]
Thanks @alexander-fenster!

**Comment by bcoe** [comment]
@barryhammen closing this now, please let us know if you continue to have issues.
