### ISSUE TITLE
GRPC Status Code 13 when including Custom InfoType w/ Regex

### ISSUE THREAD

**Issue by mr-m0u5e** [googleapis/nodejs-dlp#465]
#### Environment details

  - OS: Ubuntu 18.04.4 LTS
  - Node.js version: v12.9.1
  - npm version: 6.14.2
  - `@google-cloud/dlp` version: 2.2.0
  - `@grpc/grpc-js` version: 0.7.7

#### Steps to reproduce

  1. Create a request with a custom InfoType that includes a regex (from example https://github.com/googleapis/nodejs-dlp/blob/164496a6374c12b7535c81db365b1dbe557695c2/samples/inspect.js#L50)
  2. Send the request

Code (using example from https://github.com/googleapis/nodejs-dlp/blob/master/samples/deid.js): 
```
  const exp = {};

  exp.deidentifyWithMask = async function (
    string,
    maskingCharacter,
    numberToMask
  ) {
    // Instantiates a client
    const dlp = new DLP.DlpServiceClient();
    // The project ID to run the API call under
    const callingProjectId = config.GOOGLE_CLOUD_PROJECTID;
    // The string to deidentify
    // const string = 'My SSN is 372819127';
    // (Optional) The maximum number of sensitive characters to mask in a match
    // If omitted from the request or set to 0,
    // the API will mask any matching characters
    // const numberToMask = 5;
    // (Optional) The character to mask matching sensitive data with
    // const maskingCharacter = 'x';
    // Construct deidentification request

    // The customInfoTypes of information to match
    // const customInfoTypes = [
    //   { infoType: { name: "REGEX_TYPE" }, regex: "[0-9]{4,10}"}];


    // The minimum likelihood required before redacting a match
    const minLikelihood = "LIKELIHOOD_UNSPECIFIED";

    // The infoTypes of information to redact
    const infoTypes = [{ name: "EMAIL_ADDRESS" }, { name: "PHONE_NUMBER" }];
    // eslint-disable-next-line max-len
    const customInfoTypes = [{ infoType: { name: "DICT_TYPE" }, dictionary: { wordList: { words: ["foo", "bar", "baz"]}}},
      { infoType: { name: "REGEX_TYPE" }, regex: "[1-9]{4}"}]; //or this "\\(\\d{3}\\) \\d{3}-\\d{4}"

    const item = {value: string};
    const request = {
      parent: dlp.projectPath(callingProjectId),
      deidentifyConfig: {
        infoTypeTransformations: {
          transformations: [
            {
              primitiveTransformation: {
                characterMaskConfig: {
                  maskingCharacter: maskingCharacter,
                  numberToMask: numberToMask,
                },
              },
            },
          ],
        },
      },
      inspectConfig: {
        minLikelihood: minLikelihood,
        infoTypes: infoTypes,
        customInfoTypes: customInfoTypes,
      },
      item: item,
    };


    try {
      // Run deidentification request
      const [response] = await dlp.deidentifyContent(request);
      const deidentifiedItem = response.item;
      console.log("REDACTED MSG ", deidentifiedItem.value);
      return deidentifiedItem.value;
    } catch (err) {
      logger.error(
        LoggingKinds.GOOGLE_DATA_LOSS_PREVENTION,
        { stack: err.stack, name: err.name, message: err.message },
      );
    }
    // [END dlp_deidentify_masking]
  };
```

Error: 
```
 jsonPayload: {
  
body: {
   message: "13 INTERNAL: Serialization failure"    
   name: "Error"    
   stack: "Error: 13 INTERNAL: Serialization failure
    at Object.callErrorFromStatus (/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.cancelWithStatus (/node_modules/@grpc/grpc-js/build/src/call-stream.js:441:14)
    at BaseUnaryInterceptingCall.sendMessageWithContext (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:266:23)
    at BaseUnaryInterceptingCall.sendMessage (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:271:14)
    at ServiceClientImpl.makeUnaryRequest (/node_modules/@grpc/grpc-js/build/src/client.js:179:14)
    at ServiceClientImpl.<anonymous> (/node_modules/@grpc/grpc-js/build/src/make-client.js:92:19)
    at /node_modules/@google-cloud/dlp/build/src/v2/dlp_service_client.js:209:41
    at /node_modules/google-gax/build/src/normalCalls/timeout.js:43:16
    at repeat (/node_modules/google-gax/build/src/normalCalls/retries.js:79:25)
    at /node_modules/google-gax/build/src/normalCalls/retries.js:112:13"    
  }
```
Removing the Regex InfoType restores the functionality.

Not sure if it's an issue on my part, or something is not right with the grpc / dlp. 
Thank you for your time.

**Comment by bcoe** [comment]
@mr-m0u5e out of curiosity, what happens if you provide an actual regex, so `/[0-9]{4,10}/` rather than a string?

**Comment by mr-m0u5e** [comment]
Hi @bcoe,
When replaced with the actual regex, I get the following error

```
 body: {
   message: "3 INVALID_ARGUMENT: `pattern` must be set."    
   name: "Error"    
   stack: "Error: 3 INVALID_ARGUMENT: `pattern` must be set.
    at Object.callErrorFromStatus (/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client.js:174:52)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:340:141)
    at Object.onReceiveStatus (/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:303:181)
    at Http2CallStream.outputStatus (/node_modules/@grpc/grpc-js/build/src/call-stream.js:114:27)
    at Http2CallStream.maybeOutputStatus (/node_modules/@grpc/grpc-js/build/src/call-stream.js:153:22)
    at Http2CallStream.endCall (/node_modules/@grpc/grpc-js/build/src/call-stream.js:140:18)
    at Http2CallStream.handleTrailers (/node_modules/@grpc/grpc-js/build/src/call-stream.js:262:14)
    at ClientHttp2Stream.emit (events.js:311:20)
    at emit (internal/http2/core.js:297:8)
    at processTicksAndRejections (internal/process/task_queues.js:87:22)"    
  }
  kind: "Error in deidentifyWithMask: "   
  level: "ERROR"   
  timestamp: "2020-04-28T17:50:44.880Z"   
 }
```

**Comment by alexander-fenster** [comment]
I'm not sure yet if it's something with gRPC or protobuf.js - I'll take a look. Thank you for this report!

**Comment by mr-m0u5e** [comment]
Hi there, was wondering if there are any updates on this issue.

**Comment by murgatroid99** [comment]
I just published grpc-js version 1.0.4 with a change that should make it provide more details when errors like this are triggered. Can you try updating your dependencies to see if that helps?

**Comment by mr-m0u5e** [comment]
Hi @murgatroid99,
After updating to grpc-js version 1.0.4, I get the following error:

**Comment by murgatroid99** [comment]
According to the `.proto` file, the [`regex` field](https://github.com/googleapis/nodejs-dlp/blob/master/protos/google/privacy/dlp/v2/storage.proto#L226) has type `CustomInfoType.Regex`, which is defined [here](https://github.com/googleapis/nodejs-dlp/blob/master/protos/google/privacy/dlp/v2/storage.proto#L118). So, that's the structure of the object that you need to pass for that field.

**Comment by mr-m0u5e** [comment]
Great! Thank you @murgatroid99 for pointing me in the right direction.
it seems the documentation is out of date - after changing the object to include "pattern", everything seems to be working as expected

`        {
          infoType: { name: "REGEX_TYPE" },
          regex: {pattern: "[1-9]{4}"},
        }`

**Comment by bcoe** [comment]
@mr-m0u5e awesome, I'm glad you're unblocked.

I'm keeping this open for now so that we know to update the documentation.

**Comment by JustinBeckwith** [comment]
@sofisl it looks like we need to update the regex in the samples in question here:
https://github.com/googleapis/nodejs-dlp/issues/465#issue-608470476

Could I trouble you to take a look?
